# Generated by Django 5.2.13 on 2026-05-02 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InstructorAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("total_students", models.IntegerField(default=0)),
                ("active_students", models.IntegerField(default=0)),
                (
                    "completion_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "avg_time_spent_minutes",
                    models.DecimalField(decimal_places=1, default=0, max_digits=8),
                ),
                ("total_lessons", models.IntegerField(default=0)),
                ("total_courses", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "instructor",
                    models.ForeignKey(
                        limit_choices_to={"role__in": ["admin", "supervisor"]},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Analytics do Instrutor",
                "verbose_name_plural": "Analytics dos Instrutores",
                "ordering": ["-date"],
                "unique_together": {("instructor", "date")},
            },
        ),
    ]
