# Generated by Django 5.2.13 on 2026-04-25 11:05

import clinical.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", clinical.models.EncryptedField(blank=True, null=True)),
                ("category", models.CharField(max_length=50)),
                ("start_date", models.DateField(default=django.utils.timezone.now)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("target_value", models.IntegerField(blank=True, null=True)),
                ("current_value", models.IntegerField(default=0)),
                ("unit", models.CharField(blank=True, max_length=50, null=True)),
                ("status", models.CharField(default="active", max_length=20)),
                ("priority", models.CharField(default="medium", max_length=20)),
                ("milestones", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clinical_goals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Journal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("content", clinical.models.EncryptedField()),
                ("entry_type", models.CharField(default="free", max_length=50)),
                ("mood_score", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journal_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MoodLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("mood", models.IntegerField()),
                ("emotions", models.JSONField(default=list)),
                ("notes", clinical.models.EncryptedField(blank=True, null=True)),
                ("activities", models.JSONField(default=list)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="RPD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("situacao", clinical.models.EncryptedField()),
                ("pensamento_automatico", clinical.models.EncryptedField()),
                ("emocoes_iniciais", models.JSONField()),
                (
                    "comportamento",
                    clinical.models.EncryptedField(blank=True, null=True),
                ),
                ("distorcoes_cognitivas", models.JSONField()),
                ("resposta_alternativa", clinical.models.EncryptedField()),
                ("emocoes_finais", models.JSONField()),
                ("grau_crenca_inicial", models.IntegerField(default=100)),
                ("grau_crenca_final", models.IntegerField(default=50)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rpds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="SafetyPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("warning_signs", models.JSONField(default=list)),
                ("coping_strategies", models.JSONField(default=list)),
                ("social_contacts", models.JSONField(default=list)),
                ("professionals", models.JSONField(default=list)),
                ("safe_places", models.JSONField(default=list)),
                ("reasons_to_live", models.JSONField(default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="safety_plan",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TriggerLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("gatilho", clinical.models.EncryptedField()),
                ("intensidade_impulso", models.IntegerField()),
                ("intensidade_final", models.IntegerField(blank=True, null=True)),
                ("tecnica_utilizada", models.CharField(max_length=100)),
                ("sucesso", models.BooleanField(default=True)),
                ("notas", clinical.models.EncryptedField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="triggers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
