# Generated by Django 5.2.13 on 2026-05-01 08:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goal",
            name="start_date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
