# Generated by Django 5.2.13 on 2026-05-02 02:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0002_alter_goal_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journal",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
