# Generated by Django 5.2.10 on 2026-04-25 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Trail",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("category", models.CharField(max_length=100)),
                ("order", models.IntegerField()),
                ("is_premium", models.BooleanField(default=False)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("narrative", "narrative"),
                            ("myth_reveal", "myth_reveal"),
                            ("resistance", "resistance"),
                            ("quiz", "quiz"),
                            ("video", "video"),
                            ("breathing", "breathing"),
                            ("reflection", "reflection"),
                        ],
                        max_length=20,
                    ),
                ),
                ("audio_url", models.CharField(blank=True, max_length=500, null=True)),
                ("content", models.JSONField()),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
