# Generated by Django 5.2.13 on 2026-04-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_course_lesson_module_delete_trail_lesson_module"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="prerequisites",
            field=models.ManyToManyField(
                blank=True, related_name="required_for", to="content.lesson"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="release_date",
            field=models.DateTimeField(
                blank=True, help_text='Para estratégia "date"', null=True
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="unlock_strategy",
            field=models.CharField(
                choices=[
                    ("immediate", "Imediato"),
                    ("sequential", "Sequencial"),
                    ("date", "Data Fixa"),
                ],
                default="immediate",
                max_length=20,
            ),
        ),
    ]
