# Generated by Django 5.2.13 on 2026-04-28 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_lesson_prerequisites_lesson_release_date_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="enrolled_students",
            field=models.ManyToManyField(
                blank=True, related_name="enrolled_courses", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courses_owned",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Instrutor",
            ),
        ),
    ]
