# Generated by Django 5.2.13 on 2026-05-02 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_course_enrolled_students_course_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("category", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_premium", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="lesson",
            name="attachment",
            field=models.FileField(
                blank=True,
                help_text="PowerPoint or other resources",
                null=True,
                upload_to="courses/attachments/",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="audio_file",
            field=models.FileField(blank=True, null=True, upload_to="courses/audio/"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="quiz_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("video", "Vídeo"),
                    ("text", "Texto"),
                    ("pdf", "PDF"),
                    ("quiz", "Quiz"),
                    ("audio", "Áudio"),
                    ("powerpoint", "PowerPoint"),
                    ("form", "Formulário"),
                ],
                default="text",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="module",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modules",
                to="content.course",
            ),
        ),
        migrations.AddField(
            model_name="module",
            name="trail",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modules",
                to="content.trail",
            ),
        ),
    ]
