# Generated by Django 5.2.13 on 2026-04-28 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("content", "0002_course_lesson_module_delete_trail_lesson_module"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LessonProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_slug", models.CharField(max_length=200)),
                ("completed_at", models.DateTimeField()),
                ("time_spent_seconds", models.PositiveIntegerField(default=0)),
                ("synced_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_entries",
                        to="content.lesson",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Progresso de Aula",
                "verbose_name_plural": "Progressos de Aulas",
                "indexes": [
                    models.Index(
                        fields=["user", "course_slug"],
                        name="progress_le_user_id_1ccf2f_idx",
                    )
                ],
                "unique_together": {("user", "lesson")},
            },
        ),
    ]
