# backend/backend/constants/error_codes.py

# Autenticação
AUTH_INVALID_TOKEN = "AUTH_INVALID_TOKEN"
AUTH_EXPIRED_TOKEN = "AUTH_EXPIRED_TOKEN"
AUTH_USER_NOT_FOUND = "AUTH_USER_NOT_FOUND"

# Clínica
CLINICAL_DATA_NOT_FOUND = "CLINICAL_DATA_NOT_FOUND"
CLINICAL_ENCRYPTION_ERROR = "CLINICAL_ENCRYPTION_ERROR"
CLINICAL_DECRYPTION_ERROR = "CLINICAL_DECRYPTION_ERROR"

# IA / Serviços Externos
AI_SERVICE_TIMEOUT = "AI_SERVICE_TIMEOUT"
AI_SERVICE_ERROR = "AI_SERVICE_ERROR"

# Infra / Rede
NETWORK_OFFLINE = "NETWORK_OFFLINE"
RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"
INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"

# Validação
VALIDATION_FAILED = "VALIDATION_FAILED"
INVALID_PAYLOAD = "INVALID_PAYLOAD"
